spring.application.name=habit-tracker-back-springboot

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update

jwt-token-secret=${JWT_TOKEN_SECRET}
jwt-token-issuer=${JWT_TOKEN_ISSUER}

server.port=${PORT:8080}