spring.application.name=habit-tracker-back-springboot

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/habit-tracker-database-postgres
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

jwt-token-secret=JWT_TOKEN_SECRET
jwt-token-issuer=JWT_TOKEN_ISSUER