spring.application.name=habit-tracker-back-springboot

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${URL_DATABASE}
spring.datasource.username=${USER_DATABASE}
spring.datasource.password=${PASSWORD_DATABASE}
spring.jpa.hibernate.ddl-auto=update

jwt-token-secret=${JWT_TOKEN_SECRET}
jwt-token-issuer=${JWT_TOKEN_ISSUER}

server.port=${PORT:8080}